all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.110, mac: 'f8:b1:56:be:15:33', disk: sda, network_interface: eth0}
        # metal1: {ansible_host: 192.168.0.111, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eth0}
          # metal2: {ansible_host: 192.168.0.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eth0}
