all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        tv: {ansible_host: 192.168.0.110, mac: 'f8:b1:56:be:15:33', disk: sda, network_interface: eno1}
        plain: {ansible_host: 192.168.0.111, mac: '34:17:eb:a3:5c:3b', disk: sda, network_interface: eno1}
        starwars: {ansible_host: 192.168.0.112, mac: 'b8:ca:3a:75:64:24', disk: sda, network_interface: eno1}
